11 init solution
dnovitsky/exsb21-t4-services pull request #10
Opened 2021-10-15 13:09 UTC by nurmukhammadsunatullaev

Project Created!

2021-10-15 13:10 UTC, nurmukhammadsunatullaev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Init solution](https://trello.com/c/3zVa5Aw9/11-init-solution)

2021-10-15 15:41 UTC, dnovitsky requested changes
@nurmukhammadsunatullaev 
Please add information into the "readme" file, how to use "swagger" locally.

2021-10-15 16:22 UTC, DoniyorJN requested changes

2021-10-15 16:22 UTC, DoniyorJN commented on SAPex/Controllers/PingController.cs
> +    [ApiController]
I prefer the direct name of the controller then abstract name
if you change the name of controller and path also will change

2021-10-15 16:22 UTC, DoniyorJN commented on SAPex/Controllers/PingController.cs
> +    [ApiController]
[Route("api/[controller]")] => api/ping

2021-10-15 16:36 UTC, DoniyorJN approved these changes

2021-10-16 12:44 UTC, dnovitsky approved these changes

2021-10-16 12:45 UTC, merged