169-create-endpoint-for-candidate-process-test-task. Added Candidate …
dnovitsky/exsb21-t4-services pull request #122
Opened 2021-12-06 21:33 UTC by MikitaYepishkin

…process test endpoint

2021-12-06 22:21 UTC, dnovitsky requested changes

2021-12-06 22:21 UTC, dnovitsky commented on BusinessLogicLayer/Services/CandidateProcessTestTaskService.cs
> +        public async Task<string> GenerateCandidateProcessTestTaskTokens(Guid processId, DateTime endTestDate)
Название метода не отражает того, что он делает. Лучше этот код вынести в контроллер или в какой-либо Process    class. Например, назвать class TestTaskEmailForCandidateProcess { ... }
И тут уже вся эта логика будет, и туда же все сервисы 'инжектите'.

2021-12-06 22:21 UTC, dnovitsky commented on BusinessLogicLayer/Interfaces/ICandidateProcessTestTaskService.cs
> +        Task<string> GenerateCandidateProcessTestTaskTokens(Guid processId, DateTime endTestDate);
Очень сложный метод, выносите его в Processor

2021-12-06 22:21 UTC, dnovitsky commented on SAPex/Controllers/CandidatesController.cs
> +                var tokenList = new List<string>() { };
Список токенов нам не нужен. Как мы и говорили, напиши код для одного случая, и потом оберни это в foreach. Весь этот код можно вынести в класс Processor.

2021-12-07 00:30 UTC, MikitaYepishkin commented on BusinessLogicLayer/Services/CandidateProcessTestTaskService.cs
> +        public async Task<string> GenerateCandidateProcessTestTaskTokens(Guid processId, DateTime endTestDate)
Fixed.

2021-12-07 00:30 UTC, MikitaYepishkin commented on SAPex/Controllers/CandidatesController.cs
> +                var tokenList = new List<string>() { };
Fixed.

2021-12-07 00:30 UTC, MikitaYepishkin commented on BusinessLogicLayer/Interfaces/ICandidateProcessTestTaskService.cs
> +        Task<string> GenerateCandidateProcessTestTaskTokens(Guid processId, DateTime endTestDate);
Fixed.

2021-12-07 14:49 UTC, dnovitsky approved these changes

2021-12-08 11:31 UTC, dnovitsky approved these changes

2021-12-08 11:31 UTC, dnavitski approved these changes

2021-12-08 11:31 UTC, dnavitski commented on SAPex/Helpers/TestTaskEmailForCandidateProcess.cs
> +                List<FileEntityModel> files = (List<FileEntityModel>)await _unitOfWork.Files.GetAllAsync();
Вот тут надо брать не все файлы, а выбрать по категории.

2021-12-08 11:31 UTC, dnavitski commented on SAPex/Helpers/TestTaskEmailForCandidateProcess.cs
> +                var file = files.Count > 0 ? files[0] : null; // From App setting?
И вот здесь не стоит использовать files[0], а надо брать FirstOrDefault(). А лучше всего сделать проверку, есть ли файлы в принципе. И если их нет, то вернуть какой-либо false. Иначе у вас срабатывает exception.

2021-12-08 11:32 UTC, merged