94 implement sapexauthservice project
dnovitsky/exsb21-t4-services pull request #39
Opened 2021-11-07 18:47 UTC by nurmukhammadsunatullaev

Created SAPexAuthService project!

2021-11-07 18:50 UTC, nurmukhammadsunatullaev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement SAPexAuthService project](https://trello.com/c/lrzbAYQz/94-implement-sapexauthservice-project)

2021-11-11 21:11 UTC, dnavitski requested changes

2021-11-11 21:11 UTC, dnavitski commented on BusinessLogicLayer/Services/LanguageService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
Please remove Task.Run()

2021-11-11 21:11 UTC, dnavitski commented on BusinessLogicLayer/Services/SandboxService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
Please remove Task.Run()

2021-11-11 21:11 UTC, dnavitski commented on DataAccessLayer/Repositories/UserRepository.cs
> +        //public override async Task<IEnumerable<UserEntityModel>>  FindByConditionAsync(Expression<Func<UserEntityModel, bool>> expression)
Please remove commented code

2021-11-11 21:11 UTC, dnavitski commented on SAPex/Controllers/FakeDB/StatusViewModel.json
> +[
Please revert file changes.

2021-11-11 21:11 UTC, dnavitski commented on SAPex/appsettings.json
> +    //"DefaultConnection": "Server=(LocalDB)\\MSSQLLocalDB;Database=SAPExDb;Trusted_Connection=True;MultipleActiveResultSets=true;"
Please comment on your personal connection string and uncomment the previous connection string.

2021-11-11 21:15 UTC, nurmukhammadsunatullaev commented on BusinessLogicLayer/Services/LanguageService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
Dear mentor but it is not my controller

2021-11-11 21:15 UTC, nurmukhammadsunatullaev commented on BusinessLogicLayer/Services/SandboxService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
this is too

2021-11-11 21:27 UTC, dnavitski commented on BusinessLogicLayer/Services/LanguageService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
await Task.Run(() => unitOfWork.SaveAsync());
this code was changed in your branch, I am sorry, you need update it

2021-11-11 21:28 UTC, dnavitski commented on BusinessLogicLayer/Services/SandboxService.cs
> +                await Task.Run(() => unitOfWork.SaveAsync());
this should be updated by yourself too
await Task.Run(() => unitOfWork.SaveAsync());

2021-11-11 22:02 UTC, dnavitski approved these changes

2021-11-11 22:03 UTC, dnovitsky approved these changes

2021-11-11 22:03 UTC, merged