105 integration of getting list of sandboxes Upd & post
dnovitsky/exsb21-t4-services pull request #67
Opened 2021-11-21 19:11 UTC by MaximPyatigor

2021-11-21 23:53 UTC, dnovitsky requested changes

2021-11-21 23:53 UTC, dnovitsky commented on DbMigrations/EntityModels/FilterParametrsEntityModel.cs
>              FirstSearchingTextString = string.Empty;
Для чего используется эта модель? Что мы храним в БД? Надо обсудить с менторами.

2021-11-21 23:53 UTC, dnovitsky commented on SAPex/Models/SandboxViewModel.cs
> +        public string CreateDate { get; set; }
Почему для полей, которые несут информацию в виде DateTime, выбрали тип string?
Какие плюсы в этом решении? Надо обсудить с менторами.

2021-11-23 00:14 UTC, MaximPyatigor commented on DbMigrations/EntityModels/FilterParametrsEntityModel.cs
>              FirstSearchingTextString = string.Empty;
модель удалена

2021-11-23 00:14 UTC, MaximPyatigor commented on SAPex/Models/SandboxViewModel.cs
> +        public string CreateDate { get; set; }
Оставлено DateTime

2021-11-23 20:25 UTC, dnavitski approved these changes

2021-11-23 20:27 UTC, dnovitsky approved these changes

2021-11-23 20:27 UTC, merged