Event Repository
dnovitsky/exsb21-t4-services pull request #68
Opened 2021-11-21 19:20 UTC by nurmukhammadsunatullaev

First of all I want to show 
I change calendar

2021-11-22 23:28 UTC, dnovitsky requested changes

2021-11-22 23:28 UTC, dnovitsky commented on BusinessLogicLayer/DtoModels/EventDtoModel.cs
> +    public enum EventType
сделай пожалуйста такую нумерацию: 
ALL = 0,
FREE = 1,
INTERVIEW = 2

2021-11-22 23:28 UTC, dnovitsky commented on DbMigrations/EntityModels/EventEntityModel.cs
> +    public class EventEntityModel : IdEntityModel
В этой моделе я бы добавил поле EventType : integer.
И можно в нём хранить значение enum.

2021-11-22 23:28 UTC, dnovitsky commented on SAPex/appsettings.json
> +    "DefaultConnection": "Server=127.0.0.1,1433;Database=SAPExDb;User Id=SA;Password=MyPass@word;"
Пожалуйста, не забывай возвращать наш дефолтовый ConnectionString.

2021-11-25 20:32 UTC, dnovitsky requested changes

2021-11-25 20:32 UTC, dnovitsky commented on SAPexSMTPMailService/SAPexSMTPMailService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Options" Version="5.0.0" />
Почему понизилась версия? Как функциональность Календаря затронула Email Service?

2021-11-25 20:32 UTC, dnovitsky commented on SapexGoogleSupportService/Interfaces/IGoogleTokenService.cs
> +        public IGoogleTokenService()
Зачем нам тут конструктор?

2021-11-25 20:32 UTC, dnovitsky commented on SAPexGoogleSupportService/Services/Authorization/GoogleTokenService.cs
> +    public class GoogleTokenService
Зачем нам этот класс?

2021-11-25 20:32 UTC, dnovitsky commented on SapexGoogleSupportService/Interfaces/IGoogleTokenService.cs
> +        public IGoogleTokenService()
И где применяется этот интерфейс?

2021-11-25 20:46 UTC, nurmukhammadsunatullaev commented on SAPexGoogleSupportService/Services/Authorization/GoogleTokenService.cs
> +    public class GoogleTokenService
Хотел рефакторед код не успел, удалил заново залил всё

2021-11-25 20:46 UTC, nurmukhammadsunatullaev commented on SapexGoogleSupportService/Interfaces/IGoogleTokenService.cs
> +        public IGoogleTokenService()
Хотел рефакторед код не успел, удалил заново залил всё

2021-11-25 20:49 UTC, nurmukhammadsunatullaev commented on SAPexSMTPMailService/SAPexSMTPMailService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Options" Version="5.0.0" />
Я не трогал email проект
Никак не связано эти проекты

2021-11-25 21:13 UTC, dnavitski approved these changes

2021-11-25 21:13 UTC, dnovitsky approved these changes

2021-11-25 21:13 UTC, merged