RefactoringFeedbackTable
dnovitsky/exsb21-t4-services pull request #73
Opened 2021-11-23 21:45 UTC by FiNly17

2021-11-23 22:07 UTC, dnavitski requested changes

2021-11-23 22:07 UTC, dnavitski commented on DbMigrations/EntityModels/FeedbackEntityModel.cs
> +        public int? MentoreGrade { get; set; }
Зачем три одинаковых поля? 
А если у нас появится ещё 2 роли? опять менять таблицу? Это не гибко.

2021-11-23 22:07 UTC, dnavitski commented on SAPex/Controllers/FeedbacksController.cs
> +                MentoreGrade = feedbackDtoCheck.MentoreGrade,
Мне видится излишество полей. Нам надо передавать такую модель, в которой видно:
* кто ставит фидбек
* кому ставит фидбек
* текстовое значение фидбека
* числовое значение фидбека

2021-11-24 20:28 UTC, FiNly17 commented on SAPex/Controllers/FeedbacksController.cs
> +                MentoreGrade = feedbackDtoCheck.MentoreGrade,
Переделал

2021-11-24 20:28 UTC, FiNly17 commented on DbMigrations/EntityModels/FeedbackEntityModel.cs
> +        public int? MentoreGrade { get; set; }
Убрал

2021-11-25 12:07 UTC, dnovitsky approved these changes

2021-11-25 12:08 UTC, dnavitski approved these changes

2021-11-25 12:08 UTC, merged