Add Unit Tests For Skills
dnovitsky/exsb21-t4-services pull request #79
Opened 2021-11-28 13:18 UTC by FiNly17

2021-11-28 20:19 UTC, dnovitsky requested changes

2021-11-28 20:19 UTC, dnovitsky commented on SAPex.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "UnitTests", "UnitTests\UnitTests.csproj", "{61BB91A3-A45F-4B58-A04B-FCC5A966952F}"
Пожалуйста, переименуй проект в 'BusinessLogicLayer.Tests'

2021-11-28 20:19 UTC, dnovitsky commented on UniTests/UnitTestSkills.cs
> +        public void Test1()
Зачем нам тут пустой тест?

2021-11-28 20:19 UTC, dnovitsky commented on UnitTests/UnitTestsSkills.cs
> +    public class UnitTestsSkills
Если ты тестируешь SkillService, тогда назови файл так - "SkillServiceTests"

2021-11-28 20:19 UTC, FiNly17 commented on SAPex.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "UnitTests", "UnitTests\UnitTests.csproj", "{61BB91A3-A45F-4B58-A04B-FCC5A966952F}"
Renamed

2021-11-28 20:27 UTC, FiNly17 commented on UnitTests/UnitTestsSkills.cs
> +    public class UnitTestsSkills
Renamed

2021-11-29 23:38 UTC, dnavitski approved these changes

2021-11-29 23:40 UTC, dnovitsky approved these changes

2021-11-29 23:40 UTC, merged